# Generated by Django 4.0 on 2021-12-22 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdevelopment',
            old_name='description',
            new_name='status',
        ),
    ]
