# Generated by Django 4.0 on 2021-12-30 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdevelopment',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
