# Generated by Django 4.0 on 2021-12-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='employment_data',
            new_name='employment_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='add',
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('0', '____'), ('1', 'CEO'), ('2', 'HR'), ('3', 'PROJECT MANAGER'), ('4', 'TECHNICAL LEAD/TEAM LEADER'), ('5', 'CHIEF ARCHITECT'), ('6', 'SOFTWARE ARCHITECT'), ('7', 'SENIOR SOFTWARE DEVELOPER'), ('8', 'SOFTWARE ENGINEER'), ('9', 'JUNIOR SOFTWARE DEVELOPER'), ('10', 'INTERN SOFTWARE DEVELOPER'), ('11', 'SOFTWARE ADMINISTRATOR'), ('12', 'ABCD')], default=None, max_length=100, null=True),
        ),
    ]
