# Generated by Django 4.0 on 2021-12-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='descriptions',
        ),
    ]
