# Generated by Django 4.0 on 2021-12-30 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdevelopment',
            name='dead_line',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectdevelopment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_fields', to='HR_management_app.project'),
        ),
        migrations.AlterField(
            model_name='projectdevelopment',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectdevelopment',
            name='team_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to='HR_management_app.user'),
        ),
    ]
