# Generated by Django 4.0 on 2021-12-22 13:05

import HR_management_app.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR_management_app', '0002_rename_description_projectdevelopment_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', HR_management_app.manager.CustomUserManager()),
            ],
        ),
    ]
