# Generated by Django 4.0 on 2021-12-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_management_app', '0002_alter_project_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_owner',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
