# Generated by Django 4.0 on 2022-01-06 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR_management_app', '0002_alter_projectdevelopment_dead_line_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('date', models.DateField(auto_now_add=True)),
                ('belong_to', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='projectdevelopment',
            old_name='team_leader',
            new_name='project_manager',
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('___', '____'), ('CEO', 'CEO'), ('HR', 'HR'), ('Project Manager', 'PROJECT MANAGER'), ('business analytics', 'BUSINESS ANALYTICS'), ('Technical Lead/Team Leader', 'TECHNICAL LEAD/TEAM LEADER'), ('Chief Architect', 'CHIEF ARCHITECT'), ('Software Architect', 'SOFTWARE ARCHITECT'), ('Senior Software Developer', 'SENIOR SOFTWARE DEVELOPER'), ('Software Engineer', 'SOFTWARE ENGINEER'), ('Junior Software Developer', 'JUNIOR SOFTWARE DEVELOPER'), ('Intern Software Developer', 'INTERN SOFTWARE DEVELOPER'), ('Software Administrator', 'SOFTWARE ADMINISTRATOR'), ('abcd', 'ABCD')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_management_app.clientdetail'),
        ),
    ]
