# Generated by Django 4.0 on 2021-12-28 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR_management_app', '0003_alter_project_project_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdevelopment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='projectdevelopment',
            name='user_id',
        ),
        migrations.AddField(
            model_name='projectdevelopment',
            name='dead_line',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='projectdevelopment',
            name='progress',
            field=models.TextField(default='working on', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='projectdevelopment',
            name='team',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectdevelopment',
            name='team_leader',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to='HR_management_app.user'),
            preserve_default=False,
        ),
    ]
