# Generated by Django 4.0 on 2022-01-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_management_app', '0004_alter_projectdevelopment_dead_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdevelopment',
            name='dead_line',
            field=models.DateField(blank=True, null=True),
        ),
    ]
