# Generated by Django 4.0 on 2022-01-04 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR_management_app', '0006_alter_projectdevelopment_dead_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdevelopment',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_fields', to='HR_management_app.project'),
        ),
        migrations.AlterField(
            model_name='projectdevelopment',
            name='team_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to='HR_management_app.user'),
        ),
    ]
